- type: entity
  id: ESBaseStationArrivals
  abstract: true
  components:
  - type: ESStationArrivals

- type: entity
  id: ESBaseStationNeutral
  parent:
  - BaseStation
  - BaseStationNews
  - BaseStationCargo
  - BaseStationJobsSpawning
  - BaseStationRecords
  - BaseStationGateway
  - BaseStationShuttles
  - BaseStationCentcomm
  - BaseStationEvacuation
  - BaseStationAlertLevels
  - BaseStationMagnet
  - BaseStationExpeditions
  - BaseStationSalvageJobs
  - BaseStationSiliconLawCrewsimov
  - BaseStationAllEventsEligible
  - BaseStationNanotrasen
  - BaseStationDeliveries
  - ESBaseStationArrivals
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
  - type: ESProducer
  - type: GridSpawn
    groups:
      trade: !type:GridSpawnGroup
        addComponents:
        - type: ProtectedGrid
        - type: TradeStation
        paths:
        - /Maps/Shuttles/trading_outpost.yml
